services:
  frontend:
    build:
      context: ./client
    container_name: sga-frontend
    restart: unless-stopped

  backend:
    build:
      context: ./server
    container_name: sga-backend
    restart: unless-stopped
    volumes:
      - ./server/storage:/app/storage
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/sga_db
    depends_on:
      - db

  proxy:
    build:
      context: ./nginx
    container_name: sga-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  db:
    image: mariadb:10.7
    container_name: sga-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: sga_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
